### ISSUE TITLE
Jquery Conflict

### ISSUE THREAD

**Issue by georgegijo** [koolphp/koolreport#11]
I integrated the koolreport with codeigniter. But jquery is in conflict smart admin ui jquery version. Can you please tell me how to avoid jquery loading from koolreport. Thanks.

**Comment by lkraav** [comment]
@georgegijo did you figure this out? We have the same question.

**Comment by koolphp** [comment]
The solution is simple that you do not include jQuery in the report, remove this following line if you have in the report:

```
use \koolreport\clients\jQuery;
```

In the latest version of KoolReport, widget will detect jQuery, if jQuery is not available then it will go to load jQuery, but if there is jQuery available (may be from your app), it will continue without loading jquery. So basically, there will be no conflict.
