### ISSUE TITLE
found error

### ISSUE THREAD

**Issue by avrahamm** [koolphp/koolreport#15]
installed via 
$ composer require koolphp/koolreport

laravel/vendor/koolphp/koolreport/src/core/ResourceManager.php
line 76, 
"path"=>asset_path,
=>
"path"=>$asset_path,

4 hours :(

**Comment by koolphp** [comment]
Thank you so so much for your finding. We will make new update asap,

**Comment by koolphp** [comment]
We have released a new version 3.0.4 with the fix as you found. Thank you!
