### ISSUE TITLE
Getting Error "Undefined offset: 0" when result is empty

### ISSUE THREAD

**Issue by BernhardK91** [koolphp/koolreport#17]
Hey there,

I am getting an "Undefined offset: 0"-Error when the result is empty. Is there a way to handle empty results?

Thank you in advance!

**Comment by koolphp** [comment]
May you post the whole error?

**Comment by BernhardK91** [comment]
Good Morning and thank you for your fast response.

Here is the full error:
`Undefined offset: 0 (View: D:\Projekte\[...]\resources\views\crm\customer\overview.blade.php)`

And here is the relevant code:
```php
Table::create([
[...]
    "grouping"=>array(
        "AUFTRAG_NUMMER"=>array(
            "calculate"=>array(
                "{sumPrice}" => array("sum","TOTAL_PRICE"),
                "{AU}" => function($store) {
                    return "Auftrags-Nr. " . $store->data()[0]['AUFTRAG_NUMMER'] . " vom " .
                        date('d.m.Y',strtotime($store->data()[0]['AU_DATUM']));
                },
[...]
        ),
    ),
    'columns' => [
[...]
    ],
]);
```

Thank you in advance!

**Comment by koolphp** [comment]
It is actually a bug that we have fixed but have not released yet. The bug report was [here](https://www.koolreport.com/forum/topics/562#p3230).

Please download the new Table.tpl.php file and help us to replace the old file in \koolreport\src\widgets\koolphp" folder.

[Table.tpl.zip](https://github.com/koolphp/koolreport/files/2705010/Table.tpl.zip)

Let me know if it solves the issue.

**Comment by BernhardK91** [comment]
I see I can handle the Undefined offset in my function like:
```php
if(isset($store->data()[0])) {
    return "Auftrags-Nr. " . $store->data()[0]['AUFTRAG_NUMMER'] . " vom " .
        date('d.m.Y', strtotime($store->data()[0]['AU_DATUM']));
}
return "";
```

But when I do so, I am getting the following Error:
`Undefined variable: i in D:\Projekte\[...]\vendor\koolphp\koolreport\src\widgets\koolphp\Table.tpl.php`

The dataStore is empty in that case, and I think that is the reason for that Error.

**Comment by koolphp** [comment]
Have you been able to replace the file? Does it work?

**Comment by BernhardK91** [comment]
> It is actually a bug that we have fixed but have not released yet. The bug report was [here](https://www.koolreport.com/forum/topics/562#p3230).
> 
> Please download the new Table.tpl.php file and help us to replace the old file in \koolreport\src\widgets\koolphp" folder.

Thank you very much! That fixed the "Undefined variable: i"-Issue. In combination with my error handling in the function that Issues is completely solved!

Thanks a lot and Merry Christmas!
