### ISSUE TITLE
3.25.1: PHP Warning: count(): Parameter must be an array or an object that implements Countable in vendor/koolphp/koolreport/src/widgets/koolphp/Table.php on line 410

### ISSUE THREAD

**Issue by lkraav** [koolphp/koolreport#22]
Post-upgrade, our DrillDown chart started throwing this notice.

Are you guys testing releases on PHP 7.2+?

https://github.com/koolphp/koolreport/blob/v3.25.1/src/widgets/koolphp/Table.php#L410 should probably be

```php
if ($this->group && count($this->group) === 0 && count($this->sorting)>0) {}
```

**Comment by koolphp** [comment]
Please upgrade to 3.25.3, the issue has been fixed.
