### ISSUE TITLE
does not work with pre-7 PHP

### ISSUE THREAD

**Issue by jazzkutya** [koolphp/koolreport#23]
Does not work on PHP below 7 because clone is a reserved word and only PHP 7 and above allows using reserved words as method names.
The clone method from datastore is the problem.
The README still says PHP 5.4 or above is required.

**Comment by dongnl** [comment]
Hi jazzkutya,

Thanks much for your valuable feedback! We've just released version 3.25.4. Please try it and let us know if it fixes this issue.

**Comment by jazzkutya** [comment]
thanks, it fixes the issue.
unfortunately while getting to know koolreport I found the code quality and reliability too lacking so I abandon using this project. I will post another issue that finally made my decision but that's all. Thank you for your understanding.
