### ISSUE TITLE
Error in pdoDataSource.php when connecting to database

### ISSUE THREAD

**Issue by TechNov** [koolphp/koolreport#30]
Hello All.
I'm getting this error when a want to use KoolReport expamples.
`Fatal error: in xxxx\www\koolreport_and_examples_3.25.4\koolreport\src\datasources\PdoDataSource.php on line 111`

My PdoDataSource.php config.
`    protected function onInit()
    {
        $connectionString = Util::get($this->params, "connectionString", "mysql:host=localhost;dbname=db_test;port=3306");
        $username = Util::get($this->params, "username", "root");
        $password = Util::get($this->params, "password", "password");
        $charset = Util::get($this->params, "utf8");
`
those DB  params are valid.
please help me

**Comment by koolreport** [comment]
What examples do you try to run? Probably the example requires database installation and you have not install database yet. You can find all database files in the "examples/databases" folder. Please import the database required in example to MySQL.

**Comment by TechNov** [comment]
Hello. thank, il resolve the probleme by sitting the config.php file in the example folder.
