### ISSUE TITLE
Why not use composer's autoloader?

### ISSUE THREAD

**Issue by adamjakab** [koolphp/koolreport#7]
Hi!
very neat ;) - I did not have time to look through source code yet but I noticed that even though we are installing with composer we are not using composer's autoloader but you have a custom autoloader (which most probably does the same thing as composer).
So the question is: Why not use composer's autoloader?

**Comment by koolphp** [comment]
You are right!! I will add this feature to make things simpler.

**Comment by koolphp** [comment]
@adamjakab :  Sorry for keeping this so long. We have made it work with composer autoload.

**Comment by lkraav** [comment]
@koolphp so is this issue closed then, or not really?

**Comment by koolphp** [comment]
It should be closed and we will close now.
